server:
  port: 443
  http-port: 11011
  ssl:
    key-store: src/main/resources/keystore.p12
    keyStoreType: PKCS12
    key-password: 123456
    key-store-password: 123456
    key-alias: tomcat
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.25:3306/cas?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  application:
    name: my-cas-server
logging:
  level:
    org:
      wzx:
        mycasserver: debug
